services:
  - type: web
    name: campus-booking-system
    runtime: docker
    envVars:
      - key: PORT
        value: "8081"
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
